### ISSUE TITLE
How to handle starting the MySQL server

### ISSUE THREAD

**Issue by asclines** [CodeSpaceHQ/SDA#10]
As discussed in #7 , there are a couple ways to start the MySQL server. How do we want to handle this?

**Comment by asclines** [comment]
@dlowrey You mention doing `mysql -u root -p password`. Thats you logging in to the MySQL server.

As for the way @kevintaing86  has `os.system("mysql.server start")` yes that is a system program. 

We need a standardized way to handle this that is easily repeatable.

**Comment by dlowrey** [comment]
On Windows it is recommended that you install MySQL Server as a Windows Service. I did this, and to start the MySQL server you can use the `NET START MYSQL57` command as an administrator to start the server and `NET STOP MYSQL57` command as an administrator to stop the server. 

If not installed as a Windows Service, you use `C:\Program Files\MySQL\MySQL Server 5.7\bin\mysqld` to start the server (along with -u username -p) for username and password prompt, and `"C:\Program Files\MySQL\MySQL Server 5.7\bin\mysqladmin" -u root shutdown` (password argument may be needed?)

Keep in mind that these file paths may vary depending on where you installed MySQL. This is where I installed it on my machine. I am unsure if these are the same for Mac OSX.

[MySQL Doc](https://dev.mysql.com/doc/refman/5.7/en/windows-start-command-line.html)

**Comment by asclines** [comment]
@dlowrey do you have Windows Bash? It might be better if we look at doing this all in a Unix platform.

**Comment by dlowrey** [comment]
@asclines I can get Bash. @kevintaing86 will have to see how to start/stop the server from it. `initdb.py` will work either way because it's just right through the MySQL Connector

Or we could just detect the OS with

    import platform
    >>> platform.system()
    'Linux'

and run the command necessary to start/stop


[Bash for Windows](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide)

**Comment by kevintaing86** [comment]
@asclines @dlowrey the way I'm doing it, is that not correct?

**Comment by asclines** [comment]
@kevintaing86 It's not so much that you are doing it wrong than we need a standard way to do that. 

@dlowrey To follow up with your comment, I guess the first thing we need to do is determine what all our system should be able to run on?

@dlowrey @kevintaing86 @ASAAR Do we want this system to be OS agnostic or require a *nix setup?

**Comment by kevintaing86** [comment]
@asclines i think it would be smart to make it OS agnostic so that anyone (our professor) can clone our repo and check out all of our stuff if she wanted, but not sure how make it _agnostic_

**Comment by asclines** [comment]
@kevintaing86 two comments above yours, @dlowrey offers a way to at least start down the agnostic route. Good call on making it so the teacher can use it.

**Comment by kevintaing86** [comment]
@asclines Ahh, I see. So we'll check which OS is on the system, then make our commands in respect to that?

**Comment by asclines** [comment]
Maybe have the startup script figure that out and place in a global variable so we dont have to keep checking?

**Comment by asclines** [comment]
We might want to look into structuring our system in a way that keeps us from making too many branches off of OS. @dlowrey @kevintaing86 how many places would the OS version make a difference?

**Comment by kevintaing86** [comment]
Off the top of my head, not sure. I know that for MacOS, the way I was doing it is fine. I haven't looked at Windows or Linux to be honest. The way I am doing it also does not ask for credentials; not sure if that is an issue.

**Comment by dlowrey** [comment]
The Python connector for MySQL should do the same thing running on Mac/Windows, I think the only place the OS would make a difference is in the start/stopping the server. Basically anything that requires python to run a command using `os.system("command here")`

@kevintaing86 with your MySQL server started manually, if you run `initdb.py` does it set up the database correctly? This would be a way to verify what I said above since you are on a Mac and I wrote it on Windows.

**Comment by kevintaing86** [comment]
@dlowrey @asclines my bad, I thought we where talking about something else. I actually haven't ran your script @dlowrey, still can't figure out a way to install MySQL module. Was planning on running it on my personal PC I have in Lubbock

**Comment by dlowrey** [comment]
@kevintaing86 I didn't install the MySQL module using python, I installed it when MySQL installed. You can install it using the MySQL installer (that you got when you installed MySQL server).

**Comment by kevintaing86** [comment]
@dlowrey ya I gave it a try, but it still doesn't recognize the module in your script when you are importing it.

**Comment by dlowrey** [comment]
@kevintaing86  Hmmmmmmm.... I am going to set it up on my Mac and see what happens.

**Comment by asclines** [comment]
@kevintaing86 try again after my PR thats about to show up. #16

**Comment by asclines** [comment]
Closing as no longer used.
