### ISSUE TITLE
Upgrading MySQL Creation Script to latest datasets

### ISSUE THREAD

**Issue by asclines** [CodeSpaceHQ/SDA#11]
Now that the datasets have been fleshed out, the MySQL Creation Script needs to be refactored to account for that. 

The script should also load the datasets into the database.

Also, @dlowrey have you put any thought towards versioning the database?

**Comment by dlowrey** [comment]
@asclines I have not thought about versioning. I will look into that.

**Comment by asclines** [comment]
@dlowrey that would be a good idea as to allow for updating the database in the future. For example, if a dataset changes.
