### ISSUE TITLE
MySQL Databse Creation Script

### ISSUE THREAD

**Issue by asclines** [CodeSpaceHQ/SDA#3]
To be used by first-time users.

This Python script will handle all MySQL database initialization.

More functionality will be added in the future but for now, this script should:
- Create a MySQL database
- Create a table for each dataset we are using, with the schemas in place.

**Comment by dlowrey** [comment]
When creating each table, do you want me to just use the scheme of that table? Or should I wait until @ASAAR is done with the schema?

**Comment by asclines** [comment]
For now go off of the datasets schema. Once @ASAAR finishes his task things may be different. Also in my task, the schema might change but I will let you know if it does

**Comment by dlowrey** [comment]
The schema for the income data set is absolutely terrible... if I am looking at the right one.

**Comment by asclines** [comment]
@dlowrey lol thats fine, ill look into cleaning that up in my task
