### ISSUE TITLE
Create initial schemas

### ISSUE THREAD

**Issue by asclines** [CodeSpaceHQ/SDA#4]
Needed for our datasets:
- Conceptional Schema
- Logical Schema

We need at least a base schema set for future improvements as our insights are fleshed out.

**Comment by asclines** [comment]
@ASAAR is there progress on this?

**Comment by isaac-gs** [comment]
@asclines They are done and uploaded, we may end up tweaking them, but I have all 3 (conceptual, logical, and physical)

**Comment by asclines** [comment]
Then this issue is closed. Future updates == Future issues
